name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Authentication Docker Hub [MyBurguer ≡]
      uses: docker/login-action@v3.2.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
    
    - name: Build the Docker image [MyBurguer ≡]
      uses: docker/build-push-action@v6.0.0
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags:
          Myburguer:${{github.run_number}}
          Myburguer:latest
